AdmonRequest.WebUI/Controllers/ReportController.cs
using AdmonRequest.Application.Constants;
using AdmonRequest.Application.Interfaces;
using AdmonRequest.WebUI.ReportParamsModel;
using AspNetCore.Reporting;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace AdmonRequest.WebUI.Controllers
{
    [Route("reports")]
    public class ReportController : Controller
    {
        private readonly IAppService _appService;
        private readonly IWebHostEnvironment _env;
        public ReportController(IAppService appService, IWebHostEnvironment env)
        {
            _appService = appService;
            _env = env;
        }

        [HttpGet("request-report")]
        public IActionResult RequestReport()
        {
            return View();
        }

        [HttpPost("request-report/view")]
        public IActionResult RequestReportView(RequestReportParamModel model)
        {
            var paymentRequestQuery = _appService.FetchAllPaymentRequest();

            if (paymentRequestQuery == null) return Json(new
            {
                error = true,
                message = "Report Parameter is required"
            });

            //Report by Date range
           // var exMessage = string.Empty;

            try
            {
                if (model.ViewByDate)
                {
                    var stDate = model.StartDate;
                    var endDate = model.EndDate;

                    if (string.IsNullOrWhiteSpace(stDate) || string.IsNullOrWhiteSpace(endDate))
                    {
                        return Json(new
                        {
                            error = true,
                            message = "Start and End Date is required"
                        });
                    }

                    var startDate = new DateTime(int.Parse(stDate.Split("-")[2]), int.Parse(stDate.Split("-")[1]), int.Parse(stDate.Split("-")[0]));
                    var lastDate = new DateTime(int.Parse(endDate.Split("-")[2]), int.Parse(endDate.Split("-")[1]), int.Parse(endDate.Split("-")[0]));

                    if (startDate > lastDate)
                    {
                        return Json(new
                        {
                            error = true,
                            message = "Start cannot be greater than End Date"
                        });
                    }

                    paymentRequestQuery = paymentRequestQuery.Where(x => x.RequestDate >= startDate && x.RequestDate <= lastDate);

                }
                else if (model.ViewByStatus)
                {
                    var status = Guid.Parse(AppConstants.ApprovalStatus.PENDING);

                    if (model.Status == "approved")
                    {
                        status = Guid.Parse(AppConstants.ApprovalStatus.APPROVED);
                    }
                    else if (model.Status == "pending")
                    {
                        status = Guid.Parse(AppConstants.ApprovalStatus.PENDING);
                    }
                    else
                    {
                        status = Guid.Parse(AppConstants.ApprovalStatus.REJECTED);
                    }

                    paymentRequestQuery = paymentRequestQuery.Where(x => x.ApprovalStatus == status);
                }

                if (!paymentRequestQuery.Any())
                {
                    return Json(new
                    {
                        error = true,
                        message = "No record for the selected parameters"
                    });
                }

                var appRootPath = _env.ContentRootPath;

                var reportRootPath = Path.Combine(appRootPath, "Reports");


                string rdlcFilePath = Path.Combine(reportRootPath, "PaymentRequestReport.rdlc");
                Dictionary<string, string> parameters = new Dictionary<string, string>();
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                Encoding.GetEncoding("windows-1252");


                LocalReport report = new LocalReport(rdlcFilePath);

                report.AddDataSource("RequestReportDataSet", paymentRequestQuery.ToList());


                var result = report.Execute(RenderType.Pdf, 1);

                var resultBase64 = Convert.ToBase64String(result.MainStream);


                var embedFrame = "<iframe src=\"{0}\" width=\"800px\" height=\"450px\"></iframe>";

                var returnString = string.Format(embedFrame, $"data:application/pdf;base64,{Uri.EscapeDataString(resultBase64)}");


                return Json(new
                {
                    error = false,
                    data = returnString
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    error = true,
                    message = ex.Message
                });
            }

        

        }

        [HttpGet("budget-summary")]
        public IActionResult BudgetSummary()
        {
            return View();
        }

        [HttpGet("ledger-report")]
        public IActionResult LedgerReport()
        {
            return View();
        }

        [HttpGet("subscriber-account-details")]
        public IActionResult SubscriberAccountDetails()
        {
            return View();
        }

        [HttpGet("consolidated-account-details")]
        public IActionResult ConsolidatedAccountDetails()
        {
            return View();
        }

        [HttpGet("budget-summary-and-amount-expended")]
        public IActionResult BudgetSummaryAndAmountExpended()
        {
            return View();
        }

        [HttpGet("trial-balance")]
        public IActionResult TrialBalance()
        {
            return View();
        }

        [HttpGet("financial-performance")]
        public IActionResult FinancialPerfomance()
        {
            return View();
        }

        [HttpGet("project-income")]
        public IActionResult ProjectIncome()
        {
            return View();
        }

    }
}

AdmonRequest.WebUI/Controllers/SetupController.cs
using AdmonRequest.Application.Interfaces;
using AdmonRequest.Application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdmonRequest.WebUI.Controllers
{
    [Route("setup")]
    public class SetupController : BaseController
    {
        private readonly IAppService _appService;
        public SetupController(IAppService appService)
        {
            _appService = appService;
        }

        [HttpGet("request-types")]
        public IActionResult RequestTypes()
        {
            return View();
        }

        [HttpPost("request-types/new")]
        public async Task<IActionResult> AddRequestTypes(RequestTypeModel model)
        {


            if (string.IsNullOrEmpty(model.Name)) return Json(new
            {
                error = true,
                message = "Request type name is required"
            });
            bool isUpdate = model.RequestTypeId != Guid.Empty;

            try
            {

                if (!isUpdate)
                {
                    var typeExists = _appService.FetchRequestTypes()
                                        .Any(x => x.Name == model.Name);

                    if (typeExists) return Json(new
                    {
                        error = true,
                        message = $"{model.Name} already exists"
                    });
                }
                

                var isAdded = await _appService.AddNewRequestType(model);

                if (isAdded)
                {
                    return Json(new
                    {
                        error = false,
                        message = "Request type was created"
                    });
                }
                else
                {
                    return Json(new
                    {
                        error = true,
                        message = "There was an error creating request type"
                    });
                }

            }
            catch (Exception)
            {
                return Json(new
                {
                    error = true,
                    message = "Internal Server Error"
                });
            }

           
        }

        
        [HttpPost]
        [Route("request-types/all/show")]
        public IActionResult ListAllRequestTypes()
        {
            var draw = Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var search = Request.Form["search[value]"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

            //Custom seach params
            var requestName = Request.Form["columns[1][search][value]"].FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;

            var query = _appService.FetchRequestTypes();

            //if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
            //{
            //    //var propertyInfo = typeof(AccountControlModel).GetProperty(sortColumn);

            //    if (sortColumnDirection == "asc")
            //    {

            //        query = query.AsQueryable().OrderBy(x => EF.Property<object>(x, sortColumn));
            //    }
            //    else
            //    {
            //        query = query.AsQueryable().OrderByDescending(x => EF.Property<object>(x, sortColumn));
            //    }

            //}

            if (!string.IsNullOrWhiteSpace(search))
            {
                query = query
                    .Where(x => x.Name.ToLower().Contains(search.ToLower())
                    );
            }

            if (!string.IsNullOrWhiteSpace(requestName))
            {
                query = query.Where(x => x.Name.ToLower().StartsWith(requestName.ToLower()));
            }
                       

            recordsTotal = query.Count();

            var requestTpes = query
                .Skip(skip).Take(pageSize);

            return Json(new
            {
                draw = draw,
                recordsFiltered = recordsTotal,
                recordsTotal = recordsTotal,
                data = requestTpes.ToList()
            });
        }


    }
}

AdmonRequest.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admon ERP MIS @ViewData["Title"]</title>
    
     <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet" type="text/css">
    <link href="~/assets/components/select2/dist/css/select2.min.css" rel="stylesheet">
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />*@
    <link href="~/assets/components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <link href="~/assets/components/dropzone/dist/dropzone.css" rel="stylesheet">
    <link href="~/assets/components/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/components/fullcalendar/dist/fullcalendar.min.css" rel="stylesheet">
    <link href="~/assets/components/perfect-scrollbar/css/perfect-scrollbar.min.css" rel="stylesheet">
    <link href="~/assets/components/slick-carousel/slick/slick.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link href="~/assets/css/main.css?version=4.4.0" rel="stylesheet">
        <link href="~/assets/icon_fonts_assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    
    <link href="~/assets/css/overrides.css" rel="stylesheet" />
    
</head>
<body class="menu-position-side menu-side-left full-screen">
    <div class="all-wrapper solid-bg-all">
        <div class="layout-w">
            @await Html.PartialAsync("_mobileMenu")
            @await Html.PartialAsync("_mainMenu")
            <div class="content-w">
                @await Html.PartialAsync("_topBar")
                <div class="content-i">
                    <div class="content-box">
                        @RenderBody()
                    </div>
                   
                </div>
            </div>
        </div>
    </div>

    <div style="display:none" class="loading-back-drop"></div>

    <div style="display:none" id="app-loader" class="loader">
        <div class="loader--dot"></div>
        <div class="loader--dot"></div>
        <div class="loader--dot"></div>
        <div class="loader--dot"></div>
        <div class="loader--dot"></div>
        <div class="loader--dot"></div>
        <div class="loader--text"></div>
    </div>

    <script src="~/assets/components/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/components/popper.js/dist/umd/popper.min.js" ></script>
    <script src="~/assets/components/moment/moment.js" ></script>
    <script src="~/assets/components/chart.js/dist/Chart.min.js" ></script>
    <script src="~/assets/components/select2/dist/js/select2.full.min.js" ></script>
    <script src="~/assets/components/jquery-bar-rating/dist/jquery.barrating.min.js" ></script>
    <script src="~/assets/components/ckeditor/ckeditor.js" ></script>
    <script src="~/assets/components/bootstrap-validator/dist/validator.min.js" ></script>
    <script src="~/assets/components/bootstrap-daterangepicker/daterangepicker.js" ></script>
    <script src="~/assets/components/ion.rangeSlider/js/ion.rangeSlider.min.js" ></script>
    <script src="~/assets/components/dropzone/dist/dropzone.js" ></script>
    <script src="~/assets/components/editable-table/mindmup-editabletable.js" ></script>
    <script src="~/assets/components/datatables.net/js/jquery.dataTables.min.js" ></script>
    <script src="~/assets/components/datatables.net-bs/js/dataTables.bootstrap.min.js" ></script>
    <script src="~/assets/components/fullcalendar/dist/fullcalendar.min.js" ></script>
    <script src="~/assets/components/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" ></script>
    <script src="~/assets/components/tether/dist/js/tether.min.js" ></script>
    <script src="~/assets/components/slick-carousel/slick/slick.min.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/util.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/alert.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/button.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/carousel.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/collapse.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/dropdown.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/modal.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/tab.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/tooltip.js" ></script>
    <script src="~/assets/components/bootstrap/js/dist/popover.js" ></script>
    <script src="~/assets/js/dataTables.bootstrap4.min.js" ></script>
    <script src="~/assets/js/datatables.buttons.min.js"></script>
    <script src="~/assets/js/jszip.min.js"></script>
    <script src="~/assets/js/pdfmake.min.js"></script>
    <script src="~/assets/js/vfs_fonts.js"></script>
    <script src="~/assets/js/buttons.html5.min.js"></script>
    <script src="~/assets/js/buttons.print.min.js"></script>
    <script src="~/assets/js/accounting.min.js" ></script>
    <script src="~/assets/js/AppUtils.js"></script>
    <script src="~/assets/js/main.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    @*<script src="~/assets/js/main.js?version=4.4.0"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdmonRequest.WebUI/Views/Shared/_ReportPartial.cshtml
<div class="modal fade modal-center-c onboarding-modal" id="reportViewerModal" tabindex="-1" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
         @*   <div class="modal-header">
                <h5 class="modal-title">
                    Request Document
                </h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>*@
            <div class="modal-body onboarding-content with-gradient">
                <span id="previewTag">

                </span>

            </div>
            <div class="modal-footer">
                <div class="btn-group">
                    <button type="button" class="btn btn-pure btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

AdmonRequest.WebUI/Views/Shared/_mainMenu.cshtml
<!--------------------
START - Main Menu
-------------------->
@{
    var isInRole = User.IsInRole("Management");
}
<div id="sideMenu" class="menu-w color-scheme-dark color-style-bright menu-position-side menu-side-left menu-layout-full sub-menu-style-over sub-menu-color-bright selected-menu-color-light menu-activated-on-hover menu-has-selected-link">
    <div class="logo-w">
        <a class="logo" href="@Url.Action("dashboard","home")">
            <div class="logo-elemen">
                <img style="width:100px" alt="logo" src="~/assets/img/logo.png">
            </div>
            <div class="logo-label">
                Admon ERP MIS
            </div>
        </a>
    </div>

    <h1 class="menu-page-header">
        Page Header
    </h1>
    <ul class="main-menu">
        <li class="sub-header">
            <span>Menus</span>
        </li>
        <li class="selected">
            <a href="@Url.Action("index","home",new{area=""})">
                <div class="icon-w">
                    <div class="os-icon os-icon-layout"></div>
                </div>
                <span>Dashboard</span>
            </a>

        </li>
        <li class="">
            <a href="@Url.Action("index","useraccount",new { area = "" })">
                <div class="icon-w">
                    <div class="os-icon os-icon-users"></div>
                </div>
                <span>User Management</span>
            </a>

        </li>

        <li class="">
            <a href="@Url.Action("requestTypes","Setup",new { area = "" })">
                <div class="icon-w">
                    <div class="os-icon os-icon-layers"></div>
                </div>
                <span>Request Types</span>
            </a>

        </li>
        <li class="">
            <a href="@Url.Action("index","AppRequest",new { area = "" })">
                <div class="icon-w">
                    <div class="os-icon os-icon-edit-32"></div>
                </div>
                <span>Staff Request</span>
            </a>
        </li>
        @if (User.IsInRole("Management"))
        {
            <li class="">
                <a href="@Url.Action("RequestApproval","AppRequest",new { area = "" })">
                    <div class="icon-w">
                        <div class="os-icon os-icon-tasks-checked"></div>
                    </div>
                    <span>Management Approvals </span>
                </a>
            </li>
        }
        <li class="">
            <a href="@Url.Action("RealtorsRegistration","AppRequest",new { area = "" })">
                <div class="icon-w">
                    <div class="os-icon os-icon-edit-32"></div>
                </div>
                <span>Realtor's registration</span>
            </a>
        </li>
        <li class="has-sub-menu">
            <a href="#">
                <div class="icon-w">
                    <div class="os-icon os-icon-grid"></div>
                </div>
                <span>Reports</span>
            </a>
            <div class="sub-menu-w">
                <div class="sub-menu-header">
                    Reports
                </div>
                <div class="sub-menu-icon">
                    <i class="os-icon os-icon-grid"></i>
                </div>

                <div class="sub-menu-i">
                    <ul class="sub-menu">
                        <li>
                            <a asp-action="RequestReport" asp-controller="Report">Payment Request Report</a>
                        </li>
                        <li>
                            <a asp-action="BudgetSummary" asp-controller="Report">Project Budget Summary</a>
                        </li>
                        <li>
                            <a asp-action="LedgerReport" asp-controller="Report">Project Ledger Report</a>
                        </li>
                        <li>
                            <a asp-action="SubscriberAccountDetails" asp-controller="Report">Subscriber Account Details</a>
                        </li>
                        <li>
                            <a asp-action="ConsolidatedAccountDetails" asp-controller="Report">Consolidated Account Details</a>
                        </li>
                        <li>
                            <a asp-action="BudgetSummaryAndAmountExpended" asp-controller="Report">Budget Summary &amp; Amount Expended</a>
                        </li>
                        <li>
                            <a asp-action="TrialBalance" asp-controller="Report">Trial Balance</a>
                        </li>
                        <li>
                            <a asp-action="FinancialPerfomance" asp-controller="Report">Statement of Financial Performance</a>
                        </li>
                        <li>
                            <a asp-action="ProjectIncome" asp-controller="Report">Project Income</a>
                        </li>
                    </ul>
                </div>
            </div>
        </li>
    </ul>

    <div style="background-image:none !important;background-color:#fff;padding:20px;position:fixed;bottom:5px" class="side-menu-magic">
        <div class="">
            <h6 style="color:#000;margin-bottom:30px">Registered to</h6>
            <img src="/assets/img/metro-logo.jpg" width="150" />
        </div>
    </div>

   
</div>
<!--------------------
END - Main Menu
-------------------->

AdmonRequest.WebUI/Views/Shared/_mobileMenu.cshtml
<!--------------------
        START - Mobile Menu
-------------------->
<div class="menu-mobile menu-activated-on-click color-scheme-dark">
    <div class="mm-logo-buttons-w">
        <a class="mm-logo" href="@Url.Action("dashboard","home",new { area = "" })"><img src="~/assets/img/logo.png"><span>Admon ERP MIS</span></a>
        <div class="mm-buttons">
            <div class="content-panel-open">
                <div class="os-icon os-icon-grid-circles"></div>
            </div>
            <div class="mobile-menu-trigger">
                <div class="os-icon os-icon-hamburger-menu-1"></div>
            </div>
        </div>
    </div>
    <div class="menu-and-user">
       <!--------------------
        START - Mobile Menu List
        -------------------->
        <ul class="main-menu">
            <li class="selected">
                <a href="@Url.Action("index","home",new { area = "" })">
                    <div class="icon-w">
                        <div class="os-icon os-icon-layout"></div>
                    </div>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="">
                <a href="@Url.Action("requestTypes","Setup",new { area = "" })">
                    <div class="icon-w">
                        <div class="os-icon os-icon-layers"></div>
                    </div>
                    <span>Request Types</span>
                </a>

            </li>
            <li class="">
                <a href="@Url.Action("index","AppRequest",new { area = "" })">
                    <div class="icon-w">
                        <div class="os-icon os-icon-edit-32"></div>
                    </div>
                    <span>Staff Request</span>
                </a>

            </li>
            @if (User.IsInRole("Management"))
            {
                <li class="">
                    <a href="@Url.Action("RequestApproval","AppRequest",new { area = "" })">
                        <div class="icon-w">
                            <div class="os-icon os-icon-tasks-checked"></div>
                        </div>
                        <span>Request Approvals </span>
                    </a>
                </li>
            }
            <li class="has-sub-menu">
                <a href="#">
                    <div class="icon-w">
                        <div class="os-icon os-icon-grid"></div>
                    </div>
                    <span>Reports</span>
                </a>
                <div class="sub-menu-w">                    
                    <div class="sub-menu-i">
                        <ul class="sub-menu">
                            <li>
                                <a asp-action="RequestReport" asp-controller="Report">Payment Request Report</a>
                            </li>
                            <li>
                                <a asp-action="BudgetSummary" asp-controller="Report">Project Budget Summary</a>
                            </li>
                            <li>
                                <a asp-action="LedgerReport" asp-controller="Report">Project Ledger Report</a>
                            </li>
                            <li>
                                <a asp-action="SubscriberAccountDetails" asp-controller="Report">Subscriber Account Details</a>
                            </li>
                            <li>
                                <a asp-action="ConsolidatedAccountDetails" asp-controller="Report">Consolidated Account Details</a>
                            </li>
                            <li>
                                <a asp-action="BudgetSummaryAndAmountExpended" asp-controller="Report">Budget Summary &amp; Amount Expende</a>
                            </li>
                            <li>
                                <a asp-action="TrialBalance" asp-controller="Report">Trial Balance</a>
                            </li>
                            <li>
                                <a asp-action="FinancialPerfomance" asp-controller="Report">Statement of Financial Performance</a>
                            </li>
                            <li>
                                <a asp-action="ProjectIncome" asp-controller="Report">Project Income</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>

        <!--------------------
        END - Mobile Menu List
        -------------------->
    
    </div>
</div>
<!--------------------
END - Mobile Menu
-------------------->

AdmonRequest.WebUI/Views/Shared/_topBar.cshtml
<!--------------------
          START - Top Bar
          -------------------->
<div class="top-bar color-scheme-light">

    <!--------------------
    START - Top Menu Controls
    -------------------->
    <div class="top-menu-controls">



        <!--------------------
        START - User avatar and menu in secondary top menu
        -------------------->
        <div class="logged-user-w">
            <div class="logged-user-i">

                <div class="avatar-w">
                    <img alt="" src="~/assets/img/user.png">
                </div>
                <div class="logged-user-menu color-style-bright">
                    <div class="logged-user-avatar-info">

                        <div class="avatar-w">
                            <img alt="" src="~/assets/img/user.png">

                        </div>
                        <div class="logged-user-info-w">

                            <div class="logged-user-name">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    var staffName = User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.GivenName);
                                    <span>
                                        @staffName.Value
                                    </span>

                                }
                            </div>
                            <div class="logged-user-role">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    var staffMail = User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.Email);
                                    <span>
                                        @staffMail.Value
                                    </span>

                                }
                                
                            </div>

                        </div>
                    </div>
                    <div class="bg-icon">
                        <i class="os-icon os-icon-wallet-loaded"></i>
                    </div>
                    <ul>


                        <li>
                            <a  href="@Url.Action("Logout","auth")"><i class="os-icon os-icon-signs-11"></i><span>Logout</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--------------------
        END - User avatar and menu in secondary top menu
        -------------------->
    </div>
    <!--------------------
    END - Top Menu Controls
    -------------------->
</div>
<!--------------------
END - Top Bar
-------------------->